name: Deploy to Production

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez pour le déploiement

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Chemin vers le répertoire local du thème
          server-dir: "/sites/refonte.passedevant.net/wp-content/themes/passedevant/"  # Chemin sur le serveur de production
          ignore:
            - "blocks/**"
          continue-on-error: true
