name: Deploy to Production

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez pour la production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install  # ou autre commande d'installation de vos dépendances

    - name: Build project
      run: npm run build  # ou autre commande de build de votre projet

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"  # ou autre dossier contenant les fichiers à déployer
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/path/to/your/production/folder"  # le chemin vers votre dossier de production sur le serveur
